apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ueransim.fullname" . }}-{{ .Values.nrGnb.name }}-config
data:
  open5gs-gnb.yaml: |
    mcc: '208'          # Mobile Country Code value
    mnc: '93'           # Mobile Network Code value (2 or 3 digits)

    nci: '0x000000010'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 7              # Tracking Area Code

    linkIp: {{ .Values.nrGnb.address }}
    ngapIp: {{ .Values.nrGnb.address }}
    gtpIp: {{ .Values.nrGnb.address }}

    # List of AMF address information
    amfConfigs:
      - address: {{ .Values.amf.address }}
        port: {{ .Values.amf.port }}

    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 1
        sd: 1

    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true
