apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ueransim.fullname" . }}-{{ .Values.nrGnb.name }}
  labels:
    {{- include "ueransim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ueransim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ueransim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ueransim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - /bin/sh
          - -c
          - ./nr-gnb -c /open5gs/config/open5gs-gnb.yaml
          volumeMounts:
          - name: open5gs-gnb-config
            mountPath: /open5gs/config/open5gs-gnb.yaml
            subPath: "open5gs-gnb.yaml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: open5gs-gnb-config
        configMap:
          name: {{ include "ueransim.fullname" . }}-{{ .Values.nrGnb.name }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
