{{- if .Values.serviceAccount.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ueransim.serviceAccountName" . }}-rolebinding
  labels:
    {{- include "ueransim.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ueransim.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "ueransim.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
